pipeline:
  inputs:
    - name: tail
      path: /logs/test.log
  outputs:
    name: opensearch
    match: *
    host: os01
    port: 9200
    tls: On
    tls.verify: Off
    tls.ca_file: /etc/pki/root/ca.pem
    tls.crt_file: /etc/pki/client/cert.pem
    tls.key_file: /etc/pki/client/key.pem