version: '3.3'

services:
  sp:
    build: ./
    expose:
      - '8443'
    networks:
      - front
      - back
    ports:
      - '8443:8443'

networks:
  front:
    driver: bridge
  back:
    driver: bridge
