# default:
#   tags:
#     - openshift

variables:
  FF_NETWORK_PER_BUILD: 1
  CI_DEBUG_SERVICES: 1

stages:
  - check
  - test
  - build

.buildah:
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_ISOLATION: chroot
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY

.images:
  parallel:
    matrix:
      - IMAGE: ["backend", "openldap", "cas"]

.check-images:
  parallel:
    matrix:
      - IMAGE: ["backend"]

lint:
  stage: check
  image: node:24-slim
  extends: .check-images
  script:
    - cd ${IMAGE}
    - npm ci
    - npm run lint:gitlab
  artifacts:
    reports:
      codequality:
        - ${IMAGE}/report.json
    
format:
  stage: check
  image: node:24-slim
  extends: .check-images
  script:
    - cd ${IMAGE}
    - npm ci
    - npm run fmt:check

typecheck:
  stage: check
  image: node:24-slim
  extends: .check-images
  script:
    - cd ${IMAGE}
    - npm ci
    - npm run check

test:
  stage: test
  image: node:24-slim
  script:
    - cd backend
    - npm ci
    - npm run test:coverage

build:
  extends:
    - .buildah
    - .images
  stage: build
  script:
    - buildah build -t "$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}" ${IMAGE}
    # - buildah push "$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}"
