version: '3'

services:
  entrypoint:
    image: nginx-ssl-oss-meetme
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    networks:
      no-internet:
        aliases:
          - api.localhost.edu
          - localhost.edu
      authnet:

  mongo:
    image: database-meetme
    networks:
      - no-internet
      - mongo-net
    volumes:
      - /var/run/meetme/mongo:/var/run/external

  mongo-jr:
    image: database-meetme
    networks:
      - no-internet
      - mongo-net
    depends_on:
      - mongo
    volumes:
      - /var/run/meetme/mongo-jr:/var/run/external

  mongo-the-third:
    image: database-meetme
    networks:
      - no-internet
      - mongo-net
    depends_on:
      - mongo
    volumes:
      - /var/run/meetme/mongo-the-third:/var/run/external

  frontend:
    image: frontend-meetme
    networks:
      - no-internet
    deploy:
      mode: replicated
      replicas: 1

  openldap:
    image: bitnami/openldap:2
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=netid1,netid2,netid3,netid4,netid5,netid6
      - LDAP_PASSWORDS=rutgers1,rutgers2,rutgers3,rutgers4,rutgers5,rutgers6
      - BITNAMI_DEBUG=true
    networks:
      authnet:
        aliases:
          - ldap.localhost.edu
    volumes:
      - ./openldap_data:/bitnami/openldap
      - ./ldaptest/eduPerson.ldif:/schema/custom.ldif
      - ./ldaptest/bootstrap.ldif:/ldifs/bootstrap.ldif

  shibboleth:
    image: shibboleth-idp-meetme
    networks:
      authnet:
      no-internet:
        aliases:
          - idp.localhost.edu
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Xmx3000m
    ports:
      - 4443:4443

networks:
  no-internet:
    driver: overlay
    attachable: true
  authnet:
    driver: overlay
    attachable: true
  mongo-net:
    driver: overlay
    attachable: true
  socat-net:
    driver: overlay
    attachable: true
