version: '3'

services:
  mongo0:
    image: mongo:latest
    environment:
      - PRIMARY=1
    entrypoint: ./database/entrypoint.sh
    networks:
      - no-internet
      - mongo-net

  mongo1:
    image: mongo:latest
    entrypoint: ./database/entrypoint.sh
    networks:
      - no-internet
      - mongo-net

  mongo2:
    image: mongo:latest
    entrypoint: ./database/entrypoint.sh
    networks:
      - no-internet
      - mongo-net

  frontend:
    build:
      context: ./frontend
      target: dev
    networks:
      - no-internet
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    networks:
      - no-internet
      - authnet
    volumes:
      - ./backend:/app
    depends_on:
      - mongo0
      - mongo1
      - mongo2
      - cas

  openldap:
    build: ./openldap/
    ports:
      - 1389:1389

  cas:
    build: cas
    ports:
     - 8443:8443
     - 8080:8080

networks:
  no-internet:
    attachable: true
  authnet:
    attachable: true
  mongo-net:
    attachable: true
