server.ssl.enabled=false
server.port=8080

cas.server.name=http://localhost:8080 
cas.server.prefix=http://localhost:8080/cas
cas.server.scope=example.org 

cas.authn.oidc.core.issuer=http://localhost:8080/cas/oidc
cas.authn.oidc.core.accepted-issuers-pattern=http:\/\/.*
cas.authn.oidc.id-token.include-id-token-claims=false 

cas.authn.oidc.core.user-defined-scopes.eduPerson=eduPersonAffiliation,eduPersonPrimaryAffiliation
cas.authn.oidc.core.claims-map.given_name=givenName

cas.authn.oidc.discovery.scopes=openid,profile,eduPerson
cas.authn.oidc.discovery.claims=eduPersonPrimaryAffiliation,eduPersonAffiliation,given_name

cas.authn.ldap[0].base-dn=ou=users,dc=example,dc=org
cas.authn.ldap[0].bind-credential=adminpassword
cas.authn.ldap[0].bind-dn=cn=admin,dc=example,dc=org
cas.authn.ldap[0].ldap-url=ldap://openldap:1389
cas.authn.ldap[0].search-filter=uid={user}

cas.authn.attribute-repository.ldap[0].base-dn=ou=users,dc=example,dc=org
cas.authn.attribute-repository.ldap[0].bind-credential=adminpassword
cas.authn.attribute-repository.ldap[0].bind-dn=cn=admin,dc=example,dc=org
cas.authn.attribute-repository.ldap[0].ldap-url=ldap://openldap:1389
cas.authn.attribute-repository.ldap[0].search-filter=uid={user}

cas.service-registry.json.location=file:/etc/cas/services

cas.monitor.endpoints.endpoint.defaults.access=ANONYMOUS
management.endpoints.web.exposure.include=*

logging.config=file:/etc/cas/config/log4j2.xml