FROM nginx:latest

ENV SITE_URL https://localhost.edu

EXPOSE 80
EXPOSE 443

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y dnsutils
RUN mkdir /logs && touch /logs/api.log 

COPY nginx-prod /etc/nginx
COPY entrypoint.sh .

CMD ./entrypoint.sh
