site_name: Meetme
site_url: https://oss.rutgers.edu
repo_name: oss/meetme
repo_url: https://github.com/oss/meetme

nav:
  - Overview: 
    - About: index.md
    - Quick Start: about.md
    - FAQ: faq.md
    - Todo List: todo.md
    - Changelog: changelog.md
  - Endpoints:
      - Overview: api/api-overview.md
      - Authentication:
          - api/auth/login.md
          - api/auth/login-callback.md
          - api/auth/logout.md
      - Calendar:
          - Calendars:
              - api/calendar/calendar/post.md
              - api/calendar/calendar/delete.md
              - api/calendar/calendar/main.md
              - api/calendar/calendar/meta.md
          - Locations:
              - api/calendar/location/get.md
              - api/calendar/location/patch.md
          - MeetingTime:
              - api/calendar/meeting_time/get.md
              - api/calendar/meeting_time/patch.md
          - Name:
              - api/calendar/name/get.md
              - api/calendar/name/patch.md
          - Owner:
              - api/calendar/owner/patch.md
          - shareLink:
              - api/calendar/shareLink/get.md
              - api/calendar/shareLink/patch.md
          - Sharing:
              - api/calendar/sharing/accept-invite.md
          - UserList:
              - api/calendar/userlist/get.md
      - Organizations:
              - api/organizations/accept.md
  - Testing:
      - testing/backend-test.md
      - testing/testing-docs.md
  - Architecture:
      - Philosophy: architecture/index.md
      - Diagrams: architecture/systems.md
      - Dependencies: architecture/dependencies.md
      - Authentication: architecture/auth.md
use_directory_urls: false

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    - content.tabs
    - navigation.tabs

plugins:
  - offline
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rutgersoss
    - icon: fontawesome/brands/github
      link: https://github.com/oss
